# Generated by Django 6.0.3 on 2026-07-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(default='Gala Doctorat', max_length=120)),
                ('nom_evenement', models.CharField(default='Derniere fete des etudiants de troisieme doctorat', max_length=180)),
                ('sous_titre', models.CharField(default='Universite Joseph Kasa-Vubu', max_length=255)),
                ('notice_client', models.TextField(default="Bienvenue. Entrez votre code billet, choisissez vos boissons dans la limite de votre categorie, puis suivez l'etat de votre commande.")),
                ('mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "configuration de l'application",
                'verbose_name_plural': "configuration de l'application",
            },
        ),
        migrations.CreateModel(
            name='TableGala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('nombre_places', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('postnom', models.CharField(blank=True, max_length=80)),
                ('prenom', models.CharField(blank=True, max_length=80)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code_billet', models.CharField(max_length=40, unique=True)),
                ('categorie_billet', models.CharField(choices=[('classique', 'Classique'), ('vip_couple', 'VIP Couple'), ('vip_corps_academique', 'VIP corps academique'), ('vip_premium', 'VIP premium')], max_length=30)),
                ('est_protocole', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='comptes.tablegala')),
            ],
            options={
                'ordering': ['nom', 'postnom', 'prenom'],
            },
        ),
    ]
