# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationapplication',
            name='messages_clients_actifs',
            field=models.BooleanField(default=True),
        ),
    ]
