# Generated by Codex on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_personne', models.PositiveSmallIntegerField(default=1)),
                ('valide_par_session', models.CharField(blank=True, max_length=120)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_billet', to='comptes.invite')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_billets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'unique_together': {('invite', 'numero_personne')},
            },
        ),
    ]
