# Generated by Codex on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def complete_existing_validations(apps, schema_editor):
    ValidationBillet = apps.get_model('validation_billet', 'ValidationBillet')
    for validation in ValidationBillet.objects.filter(confirme_le__isnull=True):
        validation.confirme_par_id = validation.valide_par_id
        validation.confirme_par_session = validation.valide_par_session
        validation.confirme_le = validation.cree_le
        validation.save(update_fields=['confirme_par', 'confirme_par_session', 'confirme_le'])


class Migration(migrations.Migration):

    dependencies = [
        ('validation_billet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validationbillet',
            name='confirme_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations_billets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validationbillet',
            name='confirme_par_session',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='validationbillet',
            name='confirme_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(complete_existing_validations, migrations.RunPython.noop),
    ]
