# Generated by Django 6.0.3 on 2026-07-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('client', 'Client'), ('protocole', 'Protocole')], max_length=20)),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comptes.invite')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
    ]
