# Generated by Django 6.0.3 on 2026-07-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_billet', models.CharField(choices=[('classique', 'Classique'), ('vip_couple', 'VIP Couple'), ('vip_corps_academique', 'VIP corps academique'), ('vip_premium', 'VIP premium')], max_length=30, unique=True)),
                ('nombre_bouteilles', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categorie_billet'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='en_attente', max_length=20)),
                ('note_client', models.TextField(blank=True)),
                ('note_protocole', models.TextField(blank=True)),
                ('stock_deduit', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour', models.DateTimeField(auto_now=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='comptes.invite')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='stock.boisson')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commande.commande')),
            ],
            options={
                'unique_together': {('commande', 'boisson')},
            },
        ),
    ]
