# Generated by Codex on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationQuotaBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_billet', models.CharField(choices=[('classique', 'Classique'), ('vip_couple', 'VIP Couple'), ('vip_corps_academique', 'VIP corps academique'), ('vip_premium', 'VIP premium')], max_length=30, unique=True)),
                ('titre', models.CharField(default='Quota indicatif', max_length=120)),
                ('nombre_bouteilles_indicatif', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indication quota billet',
                'verbose_name_plural': 'Indications quotas billets',
                'ordering': ['categorie_billet'],
            },
        ),
    ]
